services:
  - type: web
    name: dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py
    port: 10000
    envVars:
      - key: REFERRAL_URL
        value: https://gamersunivers.com/default.aspx?u=1206990
      - key: PORT
        value: 10000
      # - key: NAVIGATION_TIMEOUT
      #   value: 60000

