services:
  - type: worker
    name: referral-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python referral_bot.py

  - type: web
    name: dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py
